#!/usr/bin/env python
# $Id$
# Last modified Sun Mar  1 22:16:27 2009 on violator
# update count: 333
# -*- coding:  utf-8 -*-

""" Allow all property changes """
def main():
    return 0

if __name__ == "__main__":
  import sys
  sys.exit(main())
