#!/bin/bash
# -*- coding:  utf-8 -*-
# $Id$
# Last modified Wed Jul  8 23:21:08 2009 on violator
# Update count: 140
#
# subdms - A document management system based on subversion.
# Copyright (C) 2009  Albert Thuswaldner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

SCRIPT=`which $0`
CWD=`dirname $SCRIPT`/..
 
pyuic4 $CWD/ui/about.ui > $CWD/subdms/aboutui.py
pyuic4 $CWD/ui/commit.ui > $CWD/subdms/commitui.py
pyuic4 $CWD/ui/createdocument.ui > $CWD/subdms/createdocumentui.py
pyuic4 $CWD/ui/createproj.ui > $CWD/subdms/createprojui.py
pyuic4 $CWD/ui/documentinfo.ui > $CWD/subdms/documentinfoui.py
pyuic4 $CWD/ui/mainwindow.ui > $CWD/subdms/mainwindow.py
