#!/bin/bash
# $Id$
# Last modified Sat Mar 14 00:00:24 2009 on violator
# Update count: 105
#
# Created 2009-03-04, Albert Thuswaldner

pyuic4 ../ui/createdocument.ui > ../subdms/createdocumentui.py
pyuic4 ../ui/createproj.ui > ../subdms/createprojui.py
pyuic4 ../ui/mainwindow.ui > ../subdms/mainwindow.py
