#!/bin/bash
# $Id$
# Last modified Thu Apr 16 23:04:20 2009 on violator
# Update count: 112
#
# Created 2009-03-04, Albert Thuswaldner

pyuic4 ../ui/about.ui > ../subdms/aboutui.py
pyuic4 ../ui/commit.ui > ../subdms/commitui.py
pyuic4 ../ui/createdocument.ui > ../subdms/createdocumentui.py
pyuic4 ../ui/createproj.ui > ../subdms/createprojui.py
pyuic4 ../ui/documentinfo.ui > ../subdms/documentinfoui.py
pyuic4 ../ui/mainwindow.ui > ../subdms/mainwindow.py
