#!/bin/bash
# $Id$
# Last modified Fri Mar 20 00:29:15 2009 on violator
# Update count: 106
#
# Created 2009-03-04, Albert Thuswaldner

pyuic4 ../ui/about.ui > ../subdms/aboutui.py
pyuic4 ../ui/createdocument.ui > ../subdms/createdocumentui.py
pyuic4 ../ui/createproj.ui > ../subdms/createprojui.py
pyuic4 ../ui/mainwindow.ui > ../subdms/mainwindow.py
