#!/bin/bash
# $Id$
# Last modified Thu Mar  5 14:05:35 2009 on havoc
# Update count: 102
#
# Created 2009-03-04, Albert Thuswaldner

pyuic4 ui/createdocument.ui > src/createdocumentui.py
pyuic4 ui/createproj.ui > src/createprojui.py
pyuic4 ui/mainwindow.ui > src/mainwindow.py
