#!/usr/bin/env python
# $Id$
# Last modified Sun Apr 19 21:14:57 2009 on violator
# update count: 257
# -*- coding:  utf-8 -*-
#
# subdms - A document management system based on subversion.
# Copyright (C) 2009  Albert Thuswaldner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from subdms import lowlevel, database, repository

import pysvn

client = pysvn.Client()    
cmd = lowlevel.command()
conf = lowlevel.config()
repo = repository.repository()

print "Upgrade subdms server-side"
print "--------------------------"

# Upgrade db
db = database.sqlitedb()
doclist = db.getallrev()
print "Dump database."

# Remove old database
cmd.rm(conf.dbpath)
print "Remove old database." 
db2 = database.sqlitedb()
db2.upgradedb(doclist)

# Upgrade subversion repository layout
repo.upgraderepo()
filelist=[]
repo.walkrepoleafs(conf.repourl, filelist)
repo.upgradefilename(filelist)
print "Upgrade documents in repository."

# Upgrade hooks
repo.installhooks()

# Upgrade templates
repo.installtemplates()




