#!/usr/bin/env python
# $Id$
# Last modified Tue Apr  7 22:50:59 2009 on violator
# update count: 152
# -*- coding:  utf-8 -*-
#
# subdms - A document management system based on subversion.
# Copyright (C) 2009  Albert Thuswaldner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from subdms import lowlevel, database, repository

cmd = lowlevel.command()
conf = lowlevel.config()
repo = repository.repository()

print "Initialize subdms server-side"
print "-----------------------------"

# create workspace directory
cmd.createworkspace()
    
# create db
cmd.createdbpath()
db = database.sqlitedb()
db.createdb()

# create subversion repository and layout
repo.createrepo()

# install hooks
repo.installhooks()

# install templates
repo.installtemplates()


