#!/usr/bin/env python
# $Id$
# Last modified Wed Apr  1 00:34:54 2009 on violator
# update count: 305
# -*- coding:  utf-8 -*-
#
# subdms - A document management system based on subversion.
# Copyright (C) 2009  Albert Thuswaldner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
from PyQt4 import QtGui

from subdms import client
from subdms import commandline

if __name__ == "__main__":
    if len(sys.argv) < 2:
        # Start GUI
        app = QtGui.QApplication(sys.argv)
        clientapp = client.ClientUi()
        clientapp.show()
        sys.exit(app.exec_())
    else:
        # Start CLI
        cli = commandline.cli()
        cli.parseargs(sys.argv)

        
