#!/usr/bin/env python
# $Id$
# Last modified Fri Mar 13 22:19:22 2009 on violator
# update count: 292
# -*- coding:  utf-8 -*-

import sys
from PyQt4 import QtGui

import client

if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    clientapp = client.ClientUi()
    clientapp.show()
    sys.exit(app.exec_())
