#!/usr/bin/env python
# $Id$
# Last modified Sat Mar 14 00:17:59 2009 on violator
# update count: 293
# -*- coding:  utf-8 -*-

import sys
from PyQt4 import QtGui

import subdms.client

if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    clientapp = client.ClientUi()
    clientapp.show()
    sys.exit(app.exec_())
