#!/usr/bin/env python
# -*- coding:  utf-8 -*-
# $Id$
# Last modified Wed Jul  8 22:47:38 2009 on violator
# update count: 272
#
# subdms - A document management system based on subversion.
# Copyright (C) 2009  Albert Thuswaldner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from subdms import lowlevel, database, repository

cmd = lowlevel.command()
conf = lowlevel.config()
repo = repository.repository()

print "Upgrade subdms server-side"
print "--------------------------"

# Upgrade db
db = database.sqlitedb()
doclist = db.getallrev()
projlist = db.dumpallprojs()
print "Dump database."

# Remove old database
cmd.rm(conf.dbpath)

print "Remove old database." 
db2 = database.sqlitedb()
db2.createdb()

db2.upgradedoclist(doclist)
db2.upgradeprojlist(projlist)

# Upgrade subversion repository layout
repo = repository.repository()
print "Upgrade repository layout:"
repo.upgraderepo()
print "Upgrade documents in repository:"
repo.upgradefilename()


# Upgrade hooks
repo.installhooks()

# Upgrade templates
repo.installtemplates()




