#!/bin/bash
# $Id$
# Last modified Wed Apr 29 14:26:25 2009 on violator
# Update count: 114
# -*- coding:  utf-8 -*-
#
# subdms - A document management system based on subversion.
# Copyright (C) 2009  Albert Thuswaldner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

pyuic4 ../ui/about.ui > ../subdms/aboutui.py
pyuic4 ../ui/commit.ui > ../subdms/commitui.py
pyuic4 ../ui/createdocument.ui > ../subdms/createdocumentui.py
pyuic4 ../ui/createproj.ui > ../subdms/createprojui.py
pyuic4 ../ui/documentinfo.ui > ../subdms/documentinfoui.py
pyuic4 ../ui/mainwindow.ui > ../subdms/mainwindow.py
